recommend/urls.py
from django.conf.urls import url

from . import views

app_name = 'recommend'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^get_recommendations/$', views.get_recommendations, name='get_recommendations'),
    url(r'^get_recommendations/(?P<steam_id>[0-9]{17})/$', views.get_recommendations, name='get_recommendations')
]

steam_oracle/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('recommend.urls')),
    url(r'^admin/', admin.site.urls),
]

recommend/models.py
from django.db import models

class Game(models.Model):
	steam_id = models.CharField(max_length=200) #Validators?
	common_name = models.CharField(max_length=200) #Validators?

	def __str__(self):
		return '{}:{}'.format(self.common_name, self.steam_id)

	def __repr__(self):
		return '{}:{}'.format(self.common_name, self.steam_id)

	def __hash__(self):
		return hash(repr(self))

# Create your models here.
class Profile(models.Model):
	steam_id = models.CharField(max_length=17) #Validators?

	owned_games = models.ManyToManyField(Game, related_name='owned_games')
	played_games = models.ManyToManyField(Game, related_name='played_games')
	liked_games = models.ManyToManyField(Game, related_name='liked_games')

	def similarity(self, profile):
		profile_liked_games = set(profile.liked_games.all())
		self_liked_games = set(self.liked_games.all())

		profile_played_games = set(profile.played_games.all())
		self_played_games = set(self.played_games.all())

		total_self = len(self_liked_games)
		total_other = len(profile_liked_games)
		total = total_self+total_other

		diff_self = self_liked_games.difference(profile_liked_games)
		diff_other = profile_liked_games.difference(self_liked_games)

		if (len(diff_self) == len(self_liked_games)):
			return 0 #Nothing in common

		disagreements_self = 0 #Games that you like and they don't
		for game in diff_self:
			if game in profile_played_games:
				disagreements_self += 1

		disagreements_other = 0 #Games that they like and you don't
		for game in diff_other:
			if game in self_played_games:
				disagreements_other += 1

		disagreements = disagreements_self + disagreements_other
		return (total-disagreements)/total

	def __str__(self):
		return self.steam_id

	def __repr__(self):
		return self.steam_id
		
	def __hash__(self):
		return hash(repr(self))

recommend/forms.py
from django import forms

class RecommendForm(forms.Form):
   user_vanity = forms.CharField(max_length = 100, required=False)
   user_id = forms.CharField(max_length = 100, required=False)

recommend/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse

from recommend.models import Game, Profile
import recommend.steam as steam
import recommend.db_functions as db

from collections import defaultdict
import operator


def index(request):
    return render(request, 'recommend/index.html')

def get_recommendations(request, steam_id=None):
	if request.method == 'POST':
		form_response = 'Valid'
		vanity_name = request.POST['username']
		steam_id = request.POST['steam_id']

		with open('steam_api.key', 'r') as f:
			api_key = f.read()

		steamAPI = steam.SteamAPI(api_key)

		if vanity_name:
			response = steamAPI.ResolveVanityURL(vanity_name)
			if response['response']['success']:
				steam_id = response['response']['steamid']

		#Validation is required on on the user input, for now assuming correct
		user_profile = db.add_profile(steam_id)

		games_response = steamAPI.GetOwnedGames(steam_id)
		user_games = games_response['response']['games']
		for game in user_games:
			app_id = game['appid']
			played = game['playtime_forever'] != 0
			liked = game['playtime_forever'] >= 420 #This is the definition of a liked game at this point
			name = game['name']

			game_entry = db.add_game(app_id, name)

			user_profile.owned_games.add(game_entry)
			if played:
				user_profile.played_games.add(game_entry)
			if liked:
				user_profile.liked_games.add(game_entry)

	elif request.method == 'GET':
		user_profile = get_object_or_404(Profile, steam_id=steam_id)


	count_tot = 0
	count_query = 0
	graph = defaultdict(int)
	for game in set(user_profile.owned_games.all()) - set(user_profile.played_games.all()):
		graph[game] = 0

	for profile in Profile.objects.all():
		similarity = user_profile.similarity(profile)
		count_query += 1
		for game in profile.liked_games.all():
			count_tot += 1
			if game in graph:
				graph[game] += similarity

	print(count_tot, count_query)
	graph_sorted = [game for game, rank in sorted(graph.items(), key=operator.itemgetter(1), reverse=True)]
	context = {
		'ordered_recommendation_list': graph_sorted,
	}

	return render(request, 'recommend/recommendations.html', context)

recommend/templates/recommend/index.html
<html>
	<head>
		<title>Steam Oracle</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		{% load static %}
		<!--[if lte IE 8]><script src="{% static "recommend/assets/js/ie/html5shiv.js" %}"></script><![endif]-->
		<link rel="stylesheet" href="{% static "recommend/assets/css/main.css" %}"/>
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static "recommend/assets/css/ie9.css"%}" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static "recommend/assets/css/ie8.css"%}" /><![endif]-->
	</head>
	<body>	
	<!-- Footer -->
		<section id="footer">
			<div class="inner">
				<h2 class="major">Steam Oracle</h2>
				<p>
				Get recommendations tailored to you from the tastes of people you neither know nor care about!</p>
				<p>
				Simply identify your profile via one of the input boxes below and press "GO!". Keep in mind however that the method used to rank games is biased towards cheap/popular/multiplayer games that most people have put a fair few hours into, such as Left 4 Dead 2.
				</p>
				<form method="post" action="{% url 'recommend:get_recommendations'%}" method="POST">{% csrf_token %}
					<div class="field">
						<label for="username">username</label>
						<input type="text" name="username" id="username" placeholder="Custom URL here"/">
					</div>
					<div class="field">
						<label for="steam_id">Steam ID</label>
						<input type="text" name="steam_id" id="steam_id" placeholder="17 digit ID # here"/>
					</div>
					<ul class="actions">
						<li><input type="submit" value="Go!"/></li>
					</ul>
				</form>
				<p>By using this service, you give permission for your public steam information to be stored for use in future recommendations</p>
				<ul class="copyright">
					<li>&copy; David Buckley All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
				</ul>
			</div>
		</section>

		<!-- Scripts -->
		<script src="{% static "recommend/assets/js/skel.min.js" %}"></script>
		<script src="{% static "recommend/assets/js/jquery.min.js" %}"></script>
		<script src="{% static "recommend/assets/js/jquery.scrollex.min.js" %}"></script>
		<script src="{% static "recommend/assets/js/util.js" %}"></script>
		<!--[if lte IE 8]><script src="{% static "recommend/assets/js/ie/respond.min.js" %}"></script><![endif]-->
		<script src="{% static "recommend/assets/js/main.js" %}"></script>
	</body>
</html>

recommend/templates/recommend/recommendations.html
<html>
	<head>
		<title>Steam Oracle</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		{% load static %}
		<!--[if lte IE 8]><script src="{% static "recommend/assets/js/ie/html5shiv.js" %}"></script><![endif]-->
		<link rel="stylesheet" href="{% static "recommend/assets/css/main.css" %}"/>
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static "recommend/assets/css/ie9.css"%}" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static "recommend/assets/css/ie8.css"%}" /><![endif]-->
	</head>
	<body>	
	<!-- Footer -->
		<section id="footer">
			<div class="inner">
				<h2 class="major">Steam Oracle</h2>
				<p>
				Get recommendations tailored to you from the tastes of people you neither know nor care about!</p>
				<p>
				Below is a ranking of the unplayed games in your library. 
				</p>
				<ol>
					{% for game in ordered_recommendation_list %}
						<li><a href="steam://run/{{ game.steam_id }}/">{{ game.common_name }}</a></li>
					{% endfor %}
				</ol>
				<ul class="copyright">
					<li>&copy; David Buckley All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
				</ul>
			</div>
		</section>

		<!-- Scripts -->
		<script src="{% static "recommend/assets/js/skel.min.js" %}"></script>
		<script src="{% static "recommend/assets/js/jquery.min.js" %}"></script>
		<script src="{% static "recommend/assets/js/jquery.scrollex.min.js" %}"></script>
		<script src="{% static "recommend/assets/js/util.js" %}"></script>
		<!--[if lte IE 8]><script src="{% static "recommend/assets/js/ie/respond.min.js" %}"></script><![endif]-->
		<script src="{% static "recommend/assets/js/main.js" %}"></script>
	</body>
</html>